name: Contributor Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  trigger-security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Packj Security Audit Workflow
        uses: actions/github-script@v5
        with:
          script: |
            const github = require('@actions/github');
            const octokit = github.getOctokit('${{ secrets.GITHUB_TOKEN }}');

            const { owner, repo } = context.repo;
            const workflow_id = 'packj-security-audit.yml';

            octokit.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id
            }).then(response => {
              console.log(response);
            }).catch(error => {
              console.error(error);
              throw error;
            });
